# Generated by Django 3.2.6 on 2021-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
