# Generated by Django 3.2.6 on 2021-08-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='lesson_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customapp.videos')),
            ],
        ),
    ]
