# Generated by Django 3.2.6 on 2021-08-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0004_auto_20210822_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customapp.lesson'),
        ),
    ]
