# Generated by Django 3.2.6 on 2021-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0005_auto_20210822_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='part_no',
            field=models.IntegerField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
