# Generated by Django 3.2.6 on 2021-08-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0006_videos_part_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customapp.lesson')),
            ],
        ),
    ]
