# Generated by Django 3.2.6 on 2021-08-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0008_lesson_difficulty_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
